import JSZip from "jszip";

export interface ComponentExportFiles {
  title: string;
  slug: string;
  reactCode?: string;
  typescriptCode?: string;
  dependencies?: string[];
}

/**
 * Downloads a structured ZIP archive containing files for the component:
 * - TypeScript component (Component.tsx)
 * - React JavaScript component (Component.jsx)
 * - HTML, CSS, JS files (if available)
 * - README.md with installation & usage guidelines
 */
export async function downloadComponentZip(comp: ComponentExportFiles): Promise<void> {
  const zip = new JSZip();

  const folderName = `xui-${comp.slug}`;
  const root = zip.folder(folderName) || zip;

  // Single TypeScript + Tailwind file
  const tsCode = comp.typescriptCode || comp.reactCode || "";
  root.file(`${capitalize(comp.slug)}.tsx`, tsCode);

  // README.md
  const readmeContent = `# ${comp.title} - XUI Component

${comp.title} is a handcrafted animated UI component from **XUI** library.
Designed & curated by XUI.

## Install Dependencies:
\`\`\`bash
npm install ${comp.dependencies && comp.dependencies.length > 0 ? comp.dependencies.join(" ") : "motion lucide-react"}
\`\`\`

## Usage:
\`\`\`tsx
import ${capitalize(comp.slug)} from './${capitalize(comp.slug)}';

export default function Example() {
  return <${capitalize(comp.slug)} />;
}
\`\`\`

---
© XUI UI Platform - Built by XUI Team
`;

  root.file("README.md", readmeContent);

  const blob = await zip.generateAsync({ type: "blob" });
  triggerDownload(blob, `${folderName}.zip`);
}

/**
 * Downloads a single formatted Markdown (.md) documentation file
 */
export function downloadComponentMarkdown(comp: ComponentExportFiles): void {
  const code = comp.typescriptCode || comp.reactCode || "";
  const mdContent = `# ${comp.title} (XUI Component)

> Handcrafted animated component crafted for **XUI**.

## Dependencies
\`\`\`bash
npm install ${comp.dependencies && comp.dependencies.length > 0 ? comp.dependencies.join(" ") : "motion lucide-react"}
\`\`\`

---

## Component Code (TypeScript + Tailwind)
\`\`\`tsx
${code}
\`\`\`

---
Generated by XUI Platform (Built by XUI)
`;

  const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8" });
  triggerDownload(blob, `${comp.slug}.md`);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function capitalize(str: string) {
  return str
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}
